Add new hit indicators
crymp-net/client-server pull request #192
Opened 2024-08-20 00:10 UTC by griseraner

Adds missing hit indicator for VTOL
Replace Wars hit indicator with one that matches the Crysis 1 vehicle hit indicators

2024-08-20 00:14 UTC, griseraner commented
![ScreenShot0066](https://github.com/user-attachments/assets/005608e1-1aab-4529-b4b8-04406089d151)
![ScreenShot0064](https://github.com/user-attachments/assets/a0b995a3-ca10-4dc1-8f1c-b37fab04e3c4)

2024-08-21 19:48 UTC, ccomrade requested changes

2024-08-21 19:48 UTC, ccomrade commented on CMakeLists.txt
> +##endif()
This needs to be restored. Build is now full of warnings.

2024-09-01 09:46 UTC, ccomrade approved these changes

2024-09-01 14:10 UTC, merged